---
- name: Find installed snaps
  ansible.builtin.shell: "snap list | cut -d' ' -f 1 | tail -n+2"
  changed_when: false
  register: ohsnap

- name: Remove non-core snaps
  community.general.snap:
    name: "{{ ohsnap.stdout.split('\n') | reject('search','snapd') | reject('search','core') | list }}"
    state: absent
  register: snapout
  failed_when:
    - snapout.failed
    - "'Failed to find required executable' not in snapout.msg"
  when: ohsnap.msg != ""
  become: true

- name: Find remaining installed snaps
  ansible.builtin.shell: "snap list | cut -d' ' -f 1 | tail -n+2"
  changed_when: false
  register: ohsnap

- name: Remove core snaps
  community.general.snap:
    name: "{{ item }}"
    state: absent
  register: snapout 
  loop: "{{ ohsnap.stdout.split('\n') }}"
  failed_when:
    - snapout.failed
    - "'Failed to find required executable' not in snapout.msg"
  when: ohsnap.msg != ""
  become: true

- name: Remove Snapcraft stack
  ansible.builtin.apt:
    name:
      - snap
      - snapd
    purge: true
    autoremove: true
    state: absent
  become: true

- name: Remove snap directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /snap
    - /var/snap
    - /var/lib/snapd

- name: Add preference to not install snapd
  ansible.builtin.copy:
    src: files/snapd.preferences
    dest: /etc/apt/preferences.d/no-snap.pref
    owner: root
    group: root
    mode: 0644
  become: true
