---
- name: Converge
  hosts: all
  tasks:
    - name: Include decanonical
      ansible.builtin.include_role:
        name: ansible-decanonical
      vars:
        decanonical_purge_unneeded_pkgs: true
