---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: ubuntu2004
    box: generic/ubuntu2004
  - name: ubuntu2204
    box: generic/ubuntu2204
provisioner:
  name: ansible
verifier:
  name: testinfra
lint: |
  yamllint .
  ansible-lint
  flake8
